version: "3.9"

services:
  backend:
    build: .
    volumes:
      - .:/var/www/animal_adoption
    environment:
      - FLASK_APP=animal_adoption
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    ports:
      - "5000:5000"